nav:
  - Home: index.md
  - Getting started:
      - getting-started/index.md
      - getting-started/prerequisites.md
      - getting-started/quickstart.md
      - getting-started/installation.md
  - Architecture:
      - architecture/index.md
  - Components:
      - components/index.md
      - components/attestation-server.md
      - components/ota-service.md
      - components/esp32-akri.md
      - components/ota-agent.md
      - components/akri-dh.md
      - components/akri-integration.md
      - components/flashjob.md
      - components/flashjob-pod.md
      - components/go-akri.md
      - components/firmware-signing.md
  - Tutorials:
      - tutorials/ota-agent.md
      - tutorials/dice-auth.md
      - tutorials/ota-service.md
      - tutorials/akri-esp32.md
  - Developers:
      - developer/architecture.md
      - developer/applications.md
      - developer/building.md
        #- developer/testing.md
        #- developer/debugging.md
        #- developer/contributing.md
  - API:
      - api/index.md
      - api/openapi-spec.md
  - FAQ: faq.md
