nav:
  - Home: index.md
  - Architecture:
    - architecture/index.md
    - architecture/dice.md
    - architecture/ota_process.md
  - Getting started:
    - getting-started/prerequisites.md
    - getting-started/quickstart.md
    - getting-started/deployment-guide.md
  - Components: 
    - components/index.md
    - components/attestation-server.md
    - components/dice-auth-service.md
    - components/akri-integration.md
    - components/ota-service.md
    - components/ota-agent.md
    - components/firmware-signing.md
    - components/vaccel.md
    - components/neighbor-offloading.md
    - components/akri-discovery-handler.md
    - components/flashjob-operator.md
  - Developers:
    - developer/architecture.md
    - developer/testing.md
    - developer/debugging.md
    - developer/contributing.md
  - API:
    - api/openapi-spec.md
  - FAQ:
    - faq.md
