nav:
  - Home: index.md
  - Architecture:
    - architecture/overview.md
    - architecture/components.md
    - architecture/dataflow.md
  - Getting started:
    - getting-started/prerequisites.md
    - getting-started/quickstart.md
    - getting-started/deployment-guide.md
  - Components:
    - components/overview.md
    - Onboarding:
      - components/onboarding/overview.md
      - components/onboarding/dice-auth-service.md
      - components/onboarding/akri-integration.md
    - OTA Updates:
      - components/ota-updates/overview.md
      - components/ota-updates/ota-service.md
      - components/ota-updates/ota-agent.md
      - components/ota-updates/firmware-signing.md
    - Resource Offloading:
      - components/resource-offloading/overview.md
      - components/resource-offloading/vaccel.md
      - components/resource-offloading/neighbor-offloading.md
    - Discovery:
      - components/discovery/overview.md
      - components/discovery/akri-discovery-handler.md
    - Flashjob Operator:
      - components/flashjob-operator/overview.md
      - components/flashjob-operator/flashjob-operator.md
  - Developers:
    - developer/architecture.md
    - developer/testing.md
    - developer/debugging.md
    - developer/contributing.md
  - API:
    - api/openapi-spec.md
  - FAQ:
    - faq.md
