name: PR Build and Verify

on:
  pull_request:
    branches: ["main"]
    types: [synchronize, labeled]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run checks
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/ci.yml
    secrets: inherit
